### ISSUE TITLE
trouble running NeoDisc (ERROR: CREATION OF PERSONALIZED PROTEOMES FAILED)

### ISSUE THREAD

**Issue by CSi-Ti** [bassanilab/NeoDisc#1]
Hi NeoDisc team,

Many thanks for creating the wonderful pipeline for neoantigen discovery, which I believe will be quite useful for the research community.

I have installed it on our hpc system, and tried the test case for both panel and fastq. The panel one went well without any problems, however, the fastq mode stopped in the middle with the error message showing 'ERROR: CREATION OF PERSONALIZED PROTEOMES FAILED'(pls see the attached file 'slurm-43204806'); and when I checked the personalized proteomes log in the output file, it shows 'ERROR: Both sample 2369-tumor and Selected typings are empty'. Then I also took a look at the HLA typing part, surprisingly, it didn't seem to recognize the RNA-seq so that the output for typing was empty (see attached 2369_hlatyping.log). 

I was wondering if any of my settings was wrong, so I attached my config file (2369.config.txt), and the command I used was as below:
./NeoDisc.sh RunPipeline \
                    fastq \
                    -p 2369 \
                    -t 2369-tumor \
                    -g 2369-germline \
                    -c /gpfs/gibbs/project/caron/js4788/neodisc/test_exp/2369.config \
                    -runid exampleFQrun \
                    -cpu 24 2>&1 | tee exampleFQrun.log

Please could you kindly let me know how to fix the problem. Thanks in advance. 
 
[slurm-43204806.txt](https://github.com/user-attachments/files/17379384/slurm-43204806.txt)
[2369_hlatyping.log](https://github.com/user-attachments/files/17379421/2369_hlatyping.log)
[2369.config.txt](https://github.com/user-attachments/files/17379461/2369.config.txt)

Best,
Ruimin

**Comment by f-huber** [comment]
Dear Ruimin,

Thank you very much for your kind words about NeoDisc. 

First, I’d like to apologize for the delay in answering your question. I missed your ticket. 

Regarding your question, you’re correct, it seems that the RNAseq is not running. I believe that this may be because the « -rna » argument is missing from the command. I realized that I forgot it in the manual, I’ll update it. 

Here is the proper command to turn on RNAseq analysis:

./NeoDisc.sh RunPipeline
fastq
-p 2369
-t 2369-tumor
-g 2369-germline
-rna 2369-tumor
-c /gpfs/gibbs/project/caron/js4788/neodisc/test_exp/2369.config
-runid exampleFQrun
-cpu 24 2>&1 | tee exampleFQrun.log

It may indeed cause the problem you observed, as in this sample, WES reads seem to have been removed from the germline and tumor. Therefore they can only be typed from the RNAseq and missing the typing might lead to an error at this stage.

May I ask you to provide all the log files that are present in the PERSONALIZEDPROTEOME subfolder? This will help me understanding if that’s indeed the cause of the error. 

But if you wish to try this, please:
1. Remove the HLA_TYPING folder 
2. Restart NeoDisc, using the arguments: -rna 2369-tumor -resume 

Thank you very much by advance,

kind regards,

Florian

**Comment by CSi-Ti** [comment]
Dear Florian,

Thanks for your reply, it worked after adding the -rna argument. True, agree with you, the HLA typing from WES data didn't return any meaningful results, so it should in theory rely on the RNA data. In my previous case, the -rna was not turned on, so it consequently caused the chain effects for downstream analysis.

Best,
Ruimin

**Comment by f-huber** [comment]
Dear Ruimin,

I’m glad to read that it worked. 

Indeed, this example is a particular case, typically HLA typing is also performed on WES samples. 

Best,

Florian
